accounts/urls.py
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


from two_factor.urls import urlpatterns as tf_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('openid/', include('oidc_provider.urls', namespace='oidc_provider')),
]

urlpatterns += i18n_patterns(
    path('', include('apps.authentication.urls', namespace='authentication')),
    path('', include('apps.account.urls', namespace='account')),
    path('', include('user_sessions.urls', namespace='user_sessions')),
    path('', include(tf_urls, namespace='two_factor')),
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/account/urls.py
from django.urls import path

from . views import IndexView

app_name = 'account'


urlpatterns = [
    path('account/', IndexView.as_view(), name='index'),
]

apps/authentication/urls.py
from django.contrib.auth import views
from django.urls import path


app_name = 'authentication'


urlpatterns = [
    path('account/logout/', views.LogoutView.as_view(), name='logout'),
    path('account/password_change/', views.PasswordChangeView.as_view(), name='password_change'),
    path('account/password_change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('account/password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('account/password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('account/reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('account/reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

apps/account/models.py
from django.db import models

# Create your models here.

apps/users/models.py
import uuid

from django.utils.translation import gettext_lazy as _
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.db import models


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given email, and password.
        """
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(
        _('email address'),
        unique=True,
        error_messages={
            'unique': _("A user with that email already exists."),
        },
    )
    uuid = models.UUIDField(_('uuid'), default=uuid.uuid4, editable=False)
    first_name = models.CharField(_('first name'), max_length=50)
    middle_name = models.CharField(_('middle name'), max_length=120, blank=True)
    last_name = models.CharField(_('last name'), max_length=150)
    date_of_birth = models.DateField(_('date of birth'))
    is_active = models.BooleanField(_('active'), default=True)
    is_staff = models.BooleanField(_('staff status'), default=False)
    date_joined = models.DateTimeField(_('date joined'), auto_now_add=True)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'middle_name', 'last_name', 'date_of_birth']

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s %s' % (self.first_name, self.middle_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

apps/account/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView


class IndexView(LoginRequiredMixin, TemplateView):
    template_name = "account/index.html"

apps/authentication/views.py
from django.shortcuts import render

# Create your views here.

apps/users/views.py
from django.shortcuts import render

# Create your views here.

shared/templates/base.html
{% load i18n %}
{% load static %}
{% get_current_language as LANGUAGE_CODE %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
    <head>
        <!-- meta -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>{% block title %}{% endblock %}</title>
        {% block meta %}{% endblock %}
        <!-- stylesheets -->
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'css/fontawesome.min.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'css/custom.min.css' %}"/>
        {% block stylesheet %}{% endblock %}
        <!-- extra -->
        {% block extra %}{% endblock %}
    </head>
    <body class="d-flex flex-column vh-100 bg-gradient">
        <!-- content -->
        {% block header %}{% endblock %}
        {% block content %}{% endblock %}
        {% block footer %}{% endblock %}
        <!-- javascript -->
        <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
        {% block javascript %}{% endblock %}
    </body>
</html>

shared/templates/footer.html
{% load i18n %}
<footer class="mt-auto">
  <div class="container">
    <div class="row">
      <div class="col mt-2 text-center">
        <form class="mb-1" action="{% url 'set_language' %}" method="post">{% csrf_token %}
          <input name="next" type="hidden" value="{{ redirect_to }}">
          <select class="small shadow-sm" name="language" onchange="this.form.submit()">
            {% get_current_language as LANGUAGE_CODE %}
            {% get_available_languages as LANGUAGES %}
            {% get_language_info_list for LANGUAGES as languages %}
            {% for language in languages %}
              <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                  {{ language.name_local }} ({{ language.code }})
              </option>
            {% endfor %}
          </select>
        </form>
        <p class="small text-muted">OPENID &copy; {% now 'Y' %}</p>
      </div>
    </div>
  </div>
</footer>

shared/templates/header.html
<p>Header</p>

shared/templates/logo.html
{% load i18n %}
{% load static %}
<img class="img-fluid m-2 d-block mx-auto w-75" src="{% static 'img/logo.png' %}">

shared/templates/menu.html
<nav class="navbar navbar-expand-lg navbar-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'account:index' %}">Profile</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Services</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Privacy</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Security
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'two_factor:profile' %}">Two-factor authentication</a>
          <a class="dropdown-item" href="{% url 'user_sessions:session_list' %}">Sessions</a>
        </div>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'authentication:logout' %}">Logout</a>
      </li>
    </ul>
  </div>
</nav>

shared/templates/user_sessions/session_list.html
{% extends "base.html" %}
{% load i18n %}
{% load user_sessions %}

{% block content %}
<div class="container">
  <div class="row justify-content-md-center pt-2 pr-2 pl-2">
    <div class="col-12 col-md-10 col-lg-8 bg-white shadow rounded-lg p-0">
      {% include "menu.html" %}
    </div>
  </div>
  <div class="row justify-content-md-center pt-2 pr-2 pl-2">
    <div class="col-12 col-md-10 col-lg-8 bg-white shadow rounded-lg p-3">

      {% trans "<em>unknown on unknown</em>" as unknown_on_unknown %}
      {% trans "<em>unknown</em>" as unknown %}

      <h1>{% trans "Active Sessions" %}</h1>

      <table class="table">
        <thead>
          <tr>
            <th>{% trans "Location" %}</th>
            <th>{% trans "Device" %}</th>
            <th>{% trans "Last Activity" %}</th>
            <th>{% trans "End Session" %}</th>
          </tr>
        </thead>
        {% for object in object_list %}
          <tr {% if object.session_key == session_key %}class="active"{% endif %}>
            <td>{{ object.ip|location|default_if_none:unknown|safe }} <small>({{ object.ip }})</small></td>
            <td>{{ object.user_agent|device|default_if_none:unknown_on_unknown|safe }}</td>
            <td>
              {% if object.session_key == session_key %}
                {% blocktrans with time=object.last_activity|timesince %}{{ time }} ago (this session){% endblocktrans %}
              {% else %}
                {% blocktrans with time=object.last_activity|timesince %}{{ time }} ago{% endblocktrans %}
              {% endif %}
            </td>
            <td>
              <form method="post" action="{% url 'user_sessions:session_delete' object.pk %}">
                {% csrf_token %}
                {% if object.session_key == session_key %}
                  <button type="submit" class="btn btn-xs btn-link">{% trans "End Session" %}</button>
                {% else %}
                  <button type="submit" class="btn btn-xs btn-warning">{% trans "End Session" %}</button>
                {% endif %}
              </form>
            </td>
          </tr>
        {% endfor %}
      </table>

      {% if object_list.count > 1 %}
        <form method="post" action="{% url 'user_sessions:session_delete_other' %}">
          {% csrf_token %}
          <p>{% blocktrans %}You can also end all other sessions but the current.
            This will log you out on all other devices.{% endblocktrans %}</p>
          <button type="submit" class="btn btn-default btn-warning">{% trans "End All Other Sessions" %}</button>
        </form>
      {% endif %}

    </div>
  </div>
  {% include 'footer.html' %}
</div>
{% endblock %}